alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
