alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKg0685khbpm9paqees2e6kjki6
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table class_Student drop constraint FK7y4m2ruo06syx1a0hkcwbwpt
alter table class_Student drop constraint FKie0bafyg0j1e2ipmpj8y8ai2m
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists class_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table class_Student drop constraint FK7y4m2ruo06syx1a0hkcwbwpt
alter table class_Student drop constraint FKie0bafyg0j1e2ipmpj8y8ai2m
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists class_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table class_Student drop constraint FK7y4m2ruo06syx1a0hkcwbwpt
alter table class_Student drop constraint FKie0bafyg0j1e2ipmpj8y8ai2m
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists class_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKchk0xiwxbop4w0dkfu3u8h635
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists phone cascade
drop table if exists Student cascade
